export const PREDEFINED_AMENITIES = [
  "Wi-Fi",
  "Air Conditioning",
  "Private Bathroom",
  "Balcony",
  "TV",
  "Mini Bar",
  "Refrigerator",
  "Coffee Machine",
  "Electric Kettle",
  "Hair Dryer",
  "Wardrobe",
  "Desk",
  "Safe",
  "Room Service",
  "Breakfast Included",
  "Garden View",
  "Pyramids View",
  "Kitchenette",
  "Microwave",
  "Washing Machine",
  "Family Friendly",
  "Non-smoking",
  "Soundproof Room",
] as const;
